### PR TITLE
[WIP] Cache resource dictionaries

### PR DESCRIPTION
**Pull request by ivansg44**
This addresses #26.

We could use pickle to save the dictionaries into separate files, for use in subsequent runs.

I did some spot performance comparisons between retrieving dictionaries from .pkl files and reading them from the .csv files (as is currently done), and reading from .pkl files was faster. Particularly for larger dictionaries, and for dictionaries that were generated from other dictionaries--such as resource_permutation_terms.

JSON is another option for storing dictionaries as files, but seems to be slower.

### CODE REVIEW

**Comment by ivansg44** [comment]
Upon further discussion, we will use JSON.

**Comment by dfornika** [comment]
I'm not sure how much difference it will make, but you might want to look into `ujson`: https://github.com/esnme/ultrajson

**Comment by ivansg44** [comment]
@dfornika @Public-Health-Bioinformatics @lexmapr Can you review/help with this PR?

The time taken to run the tests in Python 3 on my machine went from ~300-350 seconds to ~30-40 seconds. The Travis CI Python 3 build also went from needing ~8-10 minutes to ~3-4 minutes.

However, the tests seem to run at the same speed on Python 2--both locally, and in Travis CI. I am not sure why this is. Perhaps a bug that can be resolved by a future pull request?

**Comment by Public-Health-Bioinformatics** [comment]
I'll take a peek tomorrow aft.

I wouldn't expect any performance comparison to be important between Travis and your dev. machine.  We have no idea how Travis accesses files, or if its running on slow servers or heavily shared ones.

**Comment by ivansg44** [comment]
@dfornika Shall we merge this?

**Pull request merged**
